version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7008:80"

  client:
    ports:
        - "3000:3000"
  proxy:
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - "80:80" 