version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}calcdistbeetwentwocordinates
    build:
      context: .
      dockerfile: CalcDistBeetwenTwoCordinates/Dockerfile
  client:
    image: client
    build:
        context: ./map-ui
        dockerfile: Dockerfile
  proxy:
    image: nginx:mainline